### ISSUE TITLE
Panic in WithError and hash of unhashable type internal.PGError

### ISSUE THREAD

**Issue by pkopac** [heroku/rollrus#26]
https://github.com/heroku/rollrus/blob/master/rollrus.go#L182

`go-pg` threw `internal.PGError`, we tried to log it `WithError(err)` and the logger panicked the worker. This definitely shouldn't happen.

The fix should be easy, though I am not 100 % sure how to do it right now.

**Comment by freeformz** [comment]
What sha/commit are you using?

**Comment by pkopac** [comment]
@freeformz the panic is happening on master, here is a replication test. It passes on Go 1.10, but fails on my machine and in production, so... it's the Go 1.12.

We use `github.com/heroku/rollrus v0.0.0-20180515183152-fc0cef2ff331`, so
https://github.com/heroku/rollrus/commit/fc0cef2ff331aebb24cd4e9ded7e20650f3d7006

https://travis-ci.org/heroku/rollrus/jobs/514185184

**Comment by freeformz** [comment]
@pkopac Can you confirm that #28 fixes your problem?

**Comment by pkopac** [comment]
I am pretty sure it does. Thanks!
