### ISSUE TITLE
Add a test for a Causer that returns nil

### ISSUE THREAD

**Issue by freeformz** [heroku/rollrus#37]
See #30

**Comment by gsempe** [comment]
I have added this test that verifies that the `extractError` function returns the original error for a Causer returning nil.

As long as `extractError` is the function dealing with `cause` value consistency I think it can be enough.

What's your point of view?

https://github.com/heroku/rollrus/blob/09bf170b78719a994a2adf2b90019d1687ab4a03/hook_test.go#L121-L143
